server:
  port: 8084
spring:
  application:
    name: payment

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://44.208.58.122:8761/eureka